---
- src: http://10.0.0.8:81/github/ahuffman/ansible-resolv
  name: ahuffman.resolv
  scm: git
- src: http://10.0.0.8:81/github/jriguera/ansible-role-configdrive
  name: jriguera.configdrive
  scm: git
- src: http://10.0.0.8:81/github/MichaelRigart/ansible-role-interfaces
  name: MichaelRigart.interfaces
  scm: git
- src: http://10.0.0.8:81/github/mrlesmithjr/ansible-manage-lvm
  name: mrlesmithjr.manage-lvm
  scm: git
- src: http://10.0.0.8:81/github/resmo/ansible-role-ntp
  name: resmo.ntp
  scm: git
#- src: singleplatform-eng.users
- src: http://10.0.0.8:81/github/stackhpc/ansible-users
  version: append
  name: singleplatform-eng.users
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-dell-powerconnect-switch
  name: stackhpc.dell-powerconnect-switch
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/drac
  name: stackhpc.drac
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/drac-facts
  name: stackhpc.drac-facts
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-grafana-conf
  name: stackhpc.grafana-conf
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-libvirt-host
  name: stackhpc.libvirt-host
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-libvirt-vm
  name: stackhpc.libvirt-vm
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-flavors
  name: stackhpc.os-flavors
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-images
  name: stackhpc.os-images
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-ironic-state
  name: stackhpc.os-ironic-state
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-networks
  name: stackhpc.os-networks
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-openstackclient
  name: stackhpc.os-openstackclient
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-projects
  name: stackhpc.os-projects
  scm: git
- src: http://10.0.0.8:81/github/stackhpc/ansible-role-os-shade
  name: stackhpc.os-shade
  scm: git
- src: http://10.0.0.8:81/github/yatesr/ansible-timezone
  name: yatesr.timezone
  scm: git
